### PR TITLE
Add native_inline_images request parameter

### PR DESCRIPTION
**Pull request by epochiero**
The _native_inline_images_ request parameter is missing in the list of valid options for **/post**, **/post/edit** and **/post/reblog**.

### CODE REVIEW

**Comment by jbenson-handy** [comment]
:100:

**Comment by johnnybenson** [comment]
:100:

**Comment by jasonpenny** [comment]
@epochiero I know this pull request is quite old, but could you fix the merge conflicts and sign the CLA?

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Pull request closed without merging**
