### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by hugovk**
Add support for Python 3.7, which needs Xenial on Travis CI (https://github.com/travis-ci/travis-ci/issues/9815).

---

Python 2.6 and 3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.6 | 2008-10-01 | 2013-10-29
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

They're also little used. Here's the pip installs for PyTumblr from PyPI for January 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  89.08% |     9,654 |
|      3.6 |   6.39% |       693 |
|      3.5 |   3.14% |       340 |
|      3.7 |   1.02% |       111 |
| null     |   0.26% |        28 |
|      3.4 |   0.10% |        11 |
| Total    |         |    10,837 |

Source: `pypistats python_minor --last-month PyTumblr`

---

This fixes the build as 2.6 and 3.7 are failing it in master:

* https://travis-ci.org/tumblr/pytumblr/builds/489395799

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by hugovk** [comment]
CLA signed.

**Comment by komapa** [comment]
@hugovk if you can sign the CLA, we can merge this PR soon after. Thank you for the contribution.

**Comment by hugovk** [comment]
@komapa Hi, I signed it on the day I opened the PR. The link now tells me:

> You previously signed this CLA on:
Thu Feb 14 2019 14:36:32 GMT+0000 (UTC)

**Comment by sndsgd** [comment]
Changes look good, and I'm still able to fetch blog info and create posts.

Nice to see that the build is passing again 💯

**Pull request merged**
