### PR TITLE
Updating contribution guideliness

### PR DESCRIPTION
**Pull request by omergulen**
It was old version so I updated it with adding the new link (https://yahoocla.herokuapp.com/) and simple guideline sentence.

### CODE REVIEW

**Comment by komapa** [comment]
We are cleaning up the CONTRIBUTING docs across all of our projects so this PR is superseded by https://github.com/tumblr/pytumblr/pull/132
Thanks for pointing this out!

**Comment by omergulen** [comment]
Tbh, I didn't get what is the difference with #132 and my PR. Why mine is closed and #132 will be accepted.
@komapa

**Comment by komapa** [comment]
The difference is that the text from #132 is what we are standardizing around in all of our repos. Yours point to the same location but the wording is different.

**Comment by omergulen** [comment]
Generally in this kind of cases, old PR is the one who would be committed with fixes.
But you know the best, what can I say, right?

**Comment by komapa** [comment]
When it comes to legal text, it is better to come from a contributor. No hard feelings, anyway nobody gets bonus points for this :) Looking forward to more contributions from you.

**Pull request closed without merging**
